### ISSUE TITLE
Portrait Layout

### ISSUE THREAD

**Issue by jbuencuerpo** [schuhumi/gnome-shell-extension-improve-osk#2]
Hi, I have been trying to use the keyboard  using the tablet in portrait  but left part of the keyboard does not appears. It is posible to resize it so it fits in both directions? My monitor is 3:2 so I guess in a 16:9 monitor will be worse.

**Comment by schuhumi** [comment]
Could you make a screenshot? For me the box the keyboard is in is too big vertically, but the keyboard fits in width. I looked a bit into why that box might be too high, but it's a rabbit hole.. Also what Gnome Shell version are you on?

![Bildschirmfoto von 2019-05-22 16-26-55](https://user-images.githubusercontent.com/5825985/58182805-90fa7e80-7cae-11e9-877f-6df100575111.png)

**Comment by jbuencuerpo** [comment]
Hi, sorry for the slow response. Here it is
![Captura de pantalla de 2019-06-29 18-42-12](https://user-images.githubusercontent.com/7101529/60399632-999f6980-9b24-11e9-9c31-9c2e5078b387.png)

**Comment by jbuencuerpo** [comment]
Ok, I have check with the adwaita theme there is no problem.

**Comment by jbuencuerpo** [comment]
I am going to close it as I think the problem was the theme. I have try other themes and there was no problem.
